name: Make blocklist
run-name: Make blocklist
on:
    push:
        branches:
            - master
        paths:
            - "src/**"
            - "domain-list.yaml"
            - "index.js"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: npm
            - name: npm install
              run: |
                  npm install --omit=dev
            - name: Run script
              run: |
                  npm run list
            - name: Commit files
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add uBlacklist.txt uBlockOrigin.txt
                  git commit -a -m "Update blocklist on github-actions[bot]"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  branch: ${{ github.head_ref }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
